# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/fleur/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),fleur)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,3a6faa8a40ff2c8a6f2fe7435c69ee933b342d0a)
$(call add-radio-file-sha1-checked,radio/gz.img,ea7f78793412554b189d32c9c39469c7da8b292b)
$(call add-radio-file-sha1-checked,radio/lk.img,db6ca8023cc0a5a8575662a3a9a5360a2dbaf312)
$(call add-radio-file-sha1-checked,radio/logo.img,fd7fc9ed28e4d2e1784a2ebbdb468c4fdbf6dcb9)
$(call add-radio-file-sha1-checked,radio/md1img.img,92420599b9edf6663d2c1ed0b35ec51190b7b00d)
$(call add-radio-file-sha1-checked,radio/pi_img.img,292256ce9278e3b32f3cb3c6bc85b05c7d490ac4)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,389b8d44b8dad68248a1711767a882a30157b150)
$(call add-radio-file-sha1-checked,radio/scp.img,300eb758045a093cb6e7b2d7998a94558da45877)
$(call add-radio-file-sha1-checked,radio/spmfw.img,16c2c9499db6d5af2f6f8dee9af5f3908d2e25e4)
$(call add-radio-file-sha1-checked,radio/sspm.img,d2ad212208076ffbfc4fd874b15dd925fedca590)
$(call add-radio-file-sha1-checked,radio/tee.img,67c75e83b9b56de3ea7025781faa5d11dc5e2320)

endif
